openapi: 3.2.0
info:
  title: Plex Media Server Events API
  version: '1.2.2

    '
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: '# API Info

    ## Content Types

    The API supports responses in both XML and JSON, and clients can request one or the other using the standard `Accept` HTTP header.'
servers:
- url: https://{IP-description}.{identifier}.plex.direct:{port}
  variables:
    IP-description:
      default: 1-2-3-4
      description: A `-` separated string of the IPv4 or IPv6 address components
    identifier:
      default: 0123456789abcdef0123456789abcdef
      description: The unique identifier of this particular PMS
    port:
      default: '32400'
security:
- user_token:
  - shared user
  - admin
tags:
- name: Events
  description: 'The server can notify clients in real-time of a wide range of events, from library scanning, to preferences being modified, to changes to media, and many other things. This is also the mechanism by which activity progress is reported.


    Two protocols for receiving the events are available: EventSource (also known as SSE), and WebSocket.'
paths:
  /:/eventsource/notifications:
    get:
      tags:
      - Events
      summary: Connect to Eventsource
      description: Connect to the event source to get a stream of events
      operationId: eventsourceGetSlash
      parameters:
      - in: query
        name: filter
        schema:
          type: array
          items:
            type: string
        description: 'By default, all events except logs are sent. A rich filtering mechanism is provided to allow clients to opt into or out of each event type using the `filters` parameter. For example:


          - `filters=-log`: All event types except logs (the default).

          - `filters=foo,bar`: Only the foo and bar event types.

          - `filters=`: All events types.

          - `filters=-foo,bar`: All event types except foo and bar.

          '
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /:/websocket/notifications:
    get:
      tags:
      - Events
      summary: Connect to WebSocket
      description: Connect to the web socket to get a stream of events
      operationId: websocketGetSlash
      parameters:
      - in: query
        name: filter
        schema:
          type: array
          items:
            type: string
        description: 'By default, all events except logs are sent. A rich filtering mechanism is provided to allow clients to opt into or out of each event type using the `filters` parameter. For example:


          - `filters=-log`: All event types except logs (the default).

          - `filters=foo,bar`: Only the foo and bar event types.

          - `filters=`: All events types.

          - `filters=-foo,bar`: All event types except foo and bar.

          '
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
components:
  securitySchemes:
    user_token:
      type: apiKey
      in: header
      name: X-Plex-Token
      description: The token which identifies the user accessing the PMS.  This is typically provided to the client by plex.tv. This can be either a traditional access token or a JWT token obtained through the JWT authentication flow.
x-tagGroups:
- name: General
  tags:
  - General
  - Library
  - Library Playlists
  - Library Collections
  - Status
  - Activities
  - Updater
  - Butler
  - Events
  - Log
  - Preferences
  - Download Queue
  - UltraBlur
  - Transcoder
- name: Media Provider
  tags:
  - Provider
  - Metadata Agents
  - Content
  - Hubs
  - Search
  - Rate
  - Playlist
  - Play Queue
  - Timeline
- name: DVR
  tags:
  - DVRs
  - Devices
  - EPG
  - Subscriptions
  - Live TV
